# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3500e6017a70c510a2b1620da24bcf0648c3befa2a70319cdb785494f83f1f856a78154783da6f5183196c8750c5baab304cd303a9e3b57afec437f9d8c16c57

test:
  secret_key_base: c354a095b3794d8f2aec82a5b4019515c1703d2ed6a0a189c8f684441e04e34433e470857718eac6fc5bf121dd6bee03b87f6956c42ac1c0d83aa680b6c05349

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
